/**
 * MUTATIONS PROVEEDOR
 */
export const SET_ITEMS = "SET_ITEMS";
export const SET_ITEMS_GETTER = "SET_ITEMS_GETTER";
export const SET_ITEM = "SET_ITEM";
export const SET_LOADING_TABLE = "SET_LOADING_TABLE";
export const SET_DISPLAY_MESSAGE = "SET_DISPLAY_MESSAGE";
export const CLEAR_FORM = "CLEAR_FORM";
export const SET_SUBMIT_ERROR = "SET_SUBMIT_ERROR";
export const SET_SUBMIT_SUCCESS = "SET_SUBMIT_SUCCESS";
export const SET_LOADING_FORM = "SET_LOADING_FORM";
export const DELETE_ITEM = "DELETE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const SET_EDIT_FORM = "SET_EDIT_FORM";
export const SET_FORM = "SET_FORM";
export const SET_STATUS = "SET_STATUS";
export const SET_LOTES = "SET_LOTES";
export const CONVERT_DATE = "CONVERT_DATE";
export const SET_CURRENT = "SET_CURRENT";
export const ADD_DETALLE_INGRESO = "ADD_DETALLE_INGRESO";
export const ADD_DETALLE_APERTURA = "ADD_DETALLE_APERTURA";
export const DELETE_DETALLE_INGRESO = "DELETE_DETALLE_INGRESO";
export const DELETE_DETALLE_APERTURA = "DELETE_DETALLE_APERTURA";
export const SET_DETALLE_INGRESO = "SET_DETALLE_INGRESO";
export const ADD_DETALLE_SALIDA = "ADD_DETALLE_SALIDA";
export const DELETE_DETALLE_SALIDA = "DELETE_DETALLE_SALIDA";
export const SET_DETALLE_SALIDA = "SET_DETALLE_SALIDA";






