/**
 * MUTATIONS PARTIDA
 */
export const SET_ITEMS = "SET_ITEMS";
export const SET_ITEM = "SET_ITEM";
export const SET_LOADING_TABLE = "SET_LOADING_TABLE";
export const SET_ERROR_TABLE = "SET_ERROR_TABLE";
export const CLEAR_FORM = "CLEAR_FORM";
export const SET_SUBMIT_ERROR = "SET_SUBMIT_ERROR";
export const SET_SUBMIT_SUCCESS = "SET_SUBMIT_SUCCESS";
export const SET_LOADING_FORM = "SET_LOADING_FORM";
export const DELETE_ITEM = "DELETE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const SET_EDIT_FORM = "SET_EDIT_FORM";
export const CONVERT_DATE = "CONVERT_DATE";
